[package]
name = "tonic-uring"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic.workspace = true
prost.workspace = true
tokio-uring.workspace = true
tower.workspace = true
hyper-util.workspace = true
hyper.workspace = true
tokio-uring-util.workspace = true